# Generated by Django 4.2.4 on 2023-08-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimages_delete_images_remove_brand_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
    ]
