# Generated by Django 4.2.4 on 2023-09-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_slag_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slag',
            new_name='slug',
        ),
    ]
