# Generated by Django 4.2.4 on 2023-09-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='weitter_link',
            new_name='twitter_link',
        ),
    ]
