# Generated by Django 4.2.4 on 2023-09-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_company_call_us_alter_company_email_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='call_us',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
